version: "3.3"

networks:
  cse_160_network:

services:
    project-1:
        image: ucmercedandeslab/tinyos_debian
        container_name: project-1
        stdin_open: true # docker run -i
        tty: true # docker run -t
        command: "bash"
        working_dir: /home
        networks: 
          cse_160_network:
            aliases:
              - "project 1"
        volumes:
            - .:/home
        logging:
          driver: "json-file"
          options:
            max-size: "200k"
            max-file: "10"
        healthcheck:
          test: bash -c "make micaz sim && python pingTest.py"
          interval: 1m30s
          timeout: 10s
          retries: 3
        labels:
          course: cse-160
          maintainer_one_name: "Adrian Darian"
          maintainer_one_email: adarian@ucmerced.edu
          maintainer_two_name: "Busher Bridi"
          maintainer_two_email: bbridi@ucmerced.edu
          version: "0.1.0"
        
